OnlineShop/Controllers/AdminController.cs
using OnlineShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShop.Models.AnotherModels;
using System.Text.RegularExpressions;

namespace OnlineShop.Controllers
{
    public class AdminController : Controller
    {

        OnlineShopContext DbOnlineShop = new OnlineShopContext();

        public ActionResult Room()
        {
            bool CheckAuth = IsAuthenticated();
            if(CheckAuth == true)
            {
                var manager = Session["Manager"].ToString();
                ViewBag.manager = manager;

                return View();
            }
            return RedirectToAction("Login", "Account");     
        }
        
        public ActionResult AddProduct()
        {
            return View();
        }

        public ActionResult EditProduct()
        {
            return View();
        }

        [HttpGet]
        public ActionResult ChangeSecreatCombination()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ChangeSecreatCombination(SecreatCombinations secreatcombination)
        {
            var phones = DbOnlineShop.Database.ExecuteSqlCommand("EXECUTE DeleteValueFromSecreatCombination");

            DbOnlineShop.SecreatCombinations.Add(secreatcombination);
            DbOnlineShop.SaveChanges();
              
            return View();
        }

        public ActionResult ShowApplies()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AddManager()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddManager(Manager manager)
        {
            //~~~~~~~~~Server validation~~~~~~~~~

            //Name Validation
            
            if (string.IsNullOrEmpty(manager.Name))
            {
                ModelState.AddModelError("Name", "The field is required");

            }

            else if (manager.Name.Length < 3 || manager.Name.Length > 50)
            {
                ModelState.AddModelError("Name", "The Name must be between 50 and 3 symbols");
            }

            //Email Validation

            if (string.IsNullOrEmpty(manager.Email))
            {
                ModelState.AddModelError("Email", "The field is required");
            }

            else if (Regex.IsMatch(manager.Email, @"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}") == false)
            {
                ModelState.AddModelError("Email", "Not correct email");
            }

            //Password Validation

            if (string.IsNullOrEmpty(manager.Password))
            {
                ModelState.AddModelError("Password", "The field is required");
            }

            else if (manager.Password.Length < 4 == true)
            {
                ModelState.AddModelError("Password", "Min value is 4");
            }

            else if (manager.Password.Length > 50 == true)
            {
                ModelState.AddModelError("Password", "Max value is 50");
            }

            if (ModelState.IsValid)
            {
                manager.DatimeRegister = DateTime.Now;
                DbOnlineShop.Managers.Add(manager);
                DbOnlineShop.SaveChanges();

            }

            return View(manager);
        }

        public ActionResult ShowStatistic()
        {
            return View();
        }

        public ActionResult InstractionAboutUsingSystem()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SignOff()
        {
            Session["Manager"] = null;
            return RedirectToAction("Login", "Account");
        }

        public bool IsAuthenticated()
        {
            if(Session["Manager"] == null)
            {
                return false;
            }

            return true;
        }



    }
}

OnlineShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShop.Models;
using System.IO;

namespace OnlineShop.Controllers
{
    public class ProductController : Controller
    {
        OnlineShopContext DbOnlineShop = new OnlineShopContext();
        //Signature for models
        [HttpGet]
        public ActionResult Console()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Console(OnlineShop.Models.Console console)
        {

            return View();
        }

        [HttpGet]
        public ActionResult Laptop()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Laptop(Laptop laptop, HttpPostedFileBase mainimage,HttpPostedFileBase additionimage1, HttpPostedFileBase additionimage2, HttpPostedFileBase additionimage3)
        {
            //Title Validation
            if (String.IsNullOrEmpty(laptop.Title))
            {
                ModelState.AddModelError("Title", "The field is required");

            }

            if (laptop.Title.Length < 3 || laptop.Title.Length > 250)
            {
                ModelState.AddModelError("Title", "The field is required");
            }

            //CodeOfProduct Validation

            if(laptop.CodeOfProduct == null)
            {
                ModelState.AddModelError("CodeOfProduct", "The field is required");
            }

            //Warrantly Validation

            if(laptop.Warrantly == null)
            {
                ModelState.AddModelError("Warrantly", "The field is required");
            }

            //Price Validation

            if (laptop.Price == null)
            {
                ModelState.AddModelError("Price", "The field is required");
            }

            if(laptop.Price < 1 || laptop.Price > 999999)
            {
                ModelState.AddModelError("Price", "Ivalid field");
            }

            //Count Validation
            if(laptop.Count == null)
            {
                ModelState.AddModelError("Count", "The field is required");
            }

            if(laptop.Count < 1 || laptop.Count > 10000)
            {
                ModelState.AddModelError("Count", "The field is required");
            }

            //Description Validation
            if (String.IsNullOrEmpty(laptop.Description))
            {
                ModelState.AddModelError("Description", "The field is required");
            }

            //MainImagePath Validation
            try
            {
               string checkval=System.IO.Path.GetFileName(mainimage.FileName);

            } catch (Exception)
            {
                ModelState.AddModelError("MainImagePath", "Put file ");
            }
            //AnotherImagesPath Validation

            //Adding images in database 

            //Main image
              string FolderName = GenerateFolderName("");

              Directory.CreateDirectory(Server.MapPath("~/Content/Images/Laptop/" + FolderName));
              Directory.CreateDirectory(Server.MapPath("~/Content/Images/Laptop/" + FolderName + "/"+ "MainImage"));

              string MainImageName= System.IO.Path.GetFileName(mainimage.FileName);

              string MainImageUrlPath = "~/Content/Images/Laptop/" + FolderName+ "/" + "MainImage/" + MainImageName;
              mainimage.SaveAs(Server.MapPath("~/Content/Images/Laptop/" + FolderName +"/"+ "MainImage/" + MainImageName));

              laptop.MainImagePath = MainImageUrlPath;
            //Additional images

            Directory.CreateDirectory(Server.MapPath("~/Content/Images/Laptop/" + FolderName + "/" + "AdditionalImages"));

            laptop.AnotherImagesPath = "";

            try
            {
                string addimage1Name = System.IO.Path.GetFileName(additionimage1.FileName);

                additionimage1.SaveAs(Server.MapPath("~/Content/Images/Laptop/" + FolderName + "/" + "AdditionalImages" + "/" + addimage1Name));

                laptop.AnotherImagesPath += "~/Content/Images/Laptop/" + FolderName + "/" + "AdditionalImages" + "/" + addimage1Name;
            }
            catch (Exception)
            {

            }

            try
            {
                string addimage2Name= System.IO.Path.GetFileName(additionimage2.FileName);

                additionimage2.SaveAs(Server.MapPath("~/Content/Images/Laptop/" + FolderName + "/" + "AdditionalImages" + "/" + addimage2Name));

                laptop.AnotherImagesPath += "||"+"~/Content/Images/Laptop/" + FolderName + "/" + "AdditionalImages" + "/"  + addimage2Name;
            }
            catch (Exception)
            {

            }

            try
            {
                string addimage3Name = System.IO.Path.GetFileName(additionimage3.FileName);

                additionimage3.SaveAs(Server.MapPath("~/Content/Images/Laptop/" + FolderName + "/" + "AdditionalImages" + "/" + addimage3Name));

                laptop.AnotherImagesPath += "||" + "~/Content/Images/Laptop/" + FolderName + "/" + "AdditionalImages" + "/" +  addimage3Name;
            }
            catch (Exception)
            {

            }

            //Adding our product into table 
            DbOnlineShop.Laptops.Add(laptop);
            DbOnlineShop.SaveChanges();
            
            return View(laptop);
        }

        [HttpGet]
        public ActionResult PC()
        {
            return View();
        }

        [HttpPost]
        public ActionResult PC(PC pC)
        {
            return View();
        }

        [HttpGet]
        public ActionResult Smartphone()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Smartphone(Smartphone smartphone)
        {
            return View();
        }

        [HttpGet]
        public ActionResult Tablet()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Tablet(Tablet tablet)
        {
            return View();
        }

        public string GenerateFolderName(string str)
        {
            str = "";
            string variants = "qwertyuiopasdf12345ghjlkz678xcvb90nm";

            Random random = new Random();

            for (int i = 0; i < 6; i++)
            {                
                int randomIndex = random.Next(0, 35);
                str += variants[randomIndex];
              
            }
            return str;
        }
    }
}

OnlineShop/Views/Admin/AddManager.cshtml
@model OnlineShop.Models.Manager
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddManager</title>
    <link href="~/Content/CSS/ValidationErrorStyle.css" type="text/css" rel="stylesheet" />
</head>
<body>
   @using (Html.BeginForm("AddManager", "Admin", FormMethod.Post))
   {

    @Html.ValidationSummary(true)
    <div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <br />
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        <br />
    </div>
    <div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <br />
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>
        <br />
    </div>
    <div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Password)
        </div>
        <br />
        <div class="editor-field">
            @Html.EditorFor(model => model.Password)
            @Html.ValidationMessageFor(model => model.Password)
        </div>
        <br />
    </div>
    <br/>
    <br/>

    <input type="submit" value="Add"/>

    <hr/>

    @Html.ActionLink("Back","Room","Admin")
   }
</body>
</html>

OnlineShop/Views/Admin/AddProduct.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddProduct</title>
</head>
<body>
 <p>@Html.ActionLink("Console", "Console", "Product")</p>
 <p>@Html.ActionLink("Laptop", "Laptop", "Product")</p>
 <p>@Html.ActionLink("PC", "PC", "Product")</p>
 <p>@Html.ActionLink("Smartphone", "Smartphone", "Product")</p>
 <p>@Html.ActionLink("Tablet", "Tablet", "Product")</p>
<hr/>

    @Html.ActionLink("Back","Product","Admin")
</body>
</html>

OnlineShop/Views/Admin/ChangeSecreatCombination.cshtml
@model OnlineShop.Models.AnotherModels.SecreatCombinations
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ChangeSecreatCombination</title>
    <link href="~/Content/CSS/ValidationErrorStyle.css" type="text/css" rel="stylesheet" />

</head>
<body>
    @using (Html.BeginForm("ChangeSecreatCombination", "Admin", FormMethod.Post))
    {
        @Html.ValidationSummary(true)
        
        <div class="editor-label">
          @Html.LabelFor(model => model.SecreatCombination)
        </div>
        <br/>
        <div class="editor-field">
            @Html.EditorFor(model => model.SecreatCombination)
            @Html.ValidationMessageFor(model=>model.SecreatCombination)
        </div>
        <br />

            <input type="submit" value="ChangeSecreatCombination" />

       }
    <hr/>
            @Html.ActionLink("Back", "Room", "Admin")

</body>
</html>

OnlineShop/Views/Admin/EditProduct.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EditProduct</title>
</head>
<body>
 
</body>
</html>

OnlineShop/Views/Admin/InstractionAboutUsingSystem.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>InstractionAboutUsingSystem</title>
</head>
<body>
  <div style="text-align:center;"><h1>Instraction about using system</h1></div>
</body>
</html>

OnlineShop/Views/Admin/Room.cshtml
    
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Room</title>
</head>
<body>

  <p>Здравствуйте, @ViewBag.manager !</p><span>@using (Html.BeginForm("SignOff", "Admin", FormMethod.Post)) { <input type="submit" value="SignOff"/> }</span>
    <br/>
    <br />
    <br />
    <br />
  <p>Действия: </p>
  <div>@Html.ActionLink("Add product", "AddProduct", "Admin")</div>
  <div>@Html.ActionLink("Change secreat combination", "ChangeSecreatCombination", "Admin")</div>
  <div>@Html.ActionLink("Show Applies", "ShowApplies", "Admin")</div>
  <div>@Html.ActionLink("Add Manager", "AddManager", "Admin")</div>
  <div>@Html.ActionLink("Show statistic", "ShowStatistic", "Admin")</div>
  <div>@Html.ActionLink("Instraction about using system", "InstractionAboutUsingSystem", "Admin")</div>
  
  <hr/>

</body>
</html>

OnlineShop/Views/Admin/ShowApplies.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowApplies</title>
</head>
<body>

</body>
</html>

OnlineShop/Views/Admin/ShowStatistic.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowStatistic</title>
</head>
<body>

</body>
</html>